### ISSUE TITLE
How to use this addon?

### ISSUE THREAD

**Issue by Sinansi** [numba/numba-scipy#28]
Hello,

Is there any hint on how to use this addon?

**Comment by stuartarchibald** [comment]
Thanks for the query. Install it with:
```
conda install -c numba numba-scipy
```
it automatically registers with Numba.

There's an example of using it in the [Numba 0.46 release notebook](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks/Numba_046_release_demo.ipynb).

**Comment by esc** [comment]
I believe this isssue is resolved and I will now close it. If any questions remain, please feel free to re-open it.
