### ISSUE TITLE
Add missing functions

### ISSUE THREAD

**Issue by KhDenys** [numba/numba-scipy#30]
How can I add the functions I need on my own? For example [scipy.special.sph_harm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sph_harm.html#scipy.special.sph_harm).

**Comment by stuartarchibald** [comment]
Thanks for expressing and interesting in numba-scipy.

The use of Numba's extension API `@overload` decorator is strongly recommended for this task. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

There's also a contributing guide here: https://numba-scipy.readthedocs.io/en/latest/developer/contributing.html

**Comment by KhDenys** [comment]
@stuartarchibald Thank you very much, I'll try.
