### ISSUE TITLE
user manual empty

### ISSUE THREAD

**Issue by Cyberface** [numba/numba-scipy#31]
Hi, first this extension to Numba looks very interesting and I am very keen to try it out so thanks for this!

Second, is there any simple examples that you could post on how to use this package? The user manual doesn't appear to have anything in it [1]

Also with this work with GPUs using numba.cuda ?

[1] https://numba-scipy.readthedocs.io/en/latest/user/index.html

Thanks!

**Comment by stuartarchibald** [comment]
@Cyberface thanks for the feedback. This project is really new so the documentation is a bit sparse at present. Supported functions are here: https://numba-scipy.readthedocs.io/en/latest/reference/index.html I guess a few lines on how to obtain the package would be useful in the user part, a pull request to add this would be most welcome :)

The answer for how to use it is in this issue: https://github.com/numba/numba-scipy/issues/28

Thanks again!

**Comment by stuartarchibald** [comment]
> Also with this work with GPUs using numba.cuda ?

Not yet, this is something we need to discuss/work out. Perhaps open a ticket for discussion if this is important to you? Thanks.

**Comment by Cyberface** [comment]
Thanks for replying!
