### ISSUE TITLE
Jitting scipy.special.jvp

### ISSUE THREAD

**Issue by KhDenys** [numba/numba-scipy#32]
To override the desired function, is it necessary to have its analog in the module [scipy.special.cython_special](https://docs.scipy.org/doc/scipy/reference/special.cython_special.html#module-scipy.special.cython_special)? Are there other options?

**Comment by seibert** [comment]
That is the preferred approach to avoid code duplication.  Otherwise the function has to be reimplemented in this project as a Numba-compilable function.
