### ISSUE TITLE
current status of SciPy special

### ISSUE THREAD

**Issue by grburgess** [numba/numba-scipy#55]
I'm unclear on what the status is for scipy.special at the moment.

Many of my reps rely on scipy >1.4 and it has trouble building on some systems now which break a lot of existing code that relied on this. I see the activity to update to newer python, but will this work soon? I've tried some of the branches but it seems I still cannot import things like gammaincc 

thanks.

**Comment by esc** [comment]
@grburgess thank you for asking about this, we are actively working on fixing this right now in #54 and I am confident to release a nw version that should be compatible with Scipy > 1.4 next week. The PR is currently being reviewed and debugged and I think there is a good chance it will fix these issues.

**Comment by grburgess** [comment]
@esc awesome! thanks!

**Comment by esc** [comment]
https://github.com/numba/numba-scipy/pull/54 has been merged now so the mainline (`master`)  should be functional again. @grburgess if you have time and inclination, we would appreciate you giving it a "test-spin".

**Comment by grburgess** [comment]
@esc already on it!

**Comment by grburgess** [comment]
@esc this works perfectly in all my packages with clean installs of the current scipy and Numba on py3.9

Thanks a lot for this and thanks to @brandonwillard

**Comment by esc** [comment]
> @esc this works perfectly in all my packages with clean installs of the current scipy and Numba on py3.9
> 
> Thanks a lot for this and thanks to @brandonwillard

Splendid, thank you! I'll close this issue now and thank you for using Numba!

**Comment by PabloRdrRbl** [comment]
Hello, which is the version that corresponds to the solution commented in this issue?

**Comment by stuartarchibald** [comment]
> Hello, which is the version that corresponds to the solution commented in this issue?

@PabloRdrRbl IIRC the latest release is 0.3.0

**Comment by PabloRdrRbl** [comment]
> > Hello, which is the version that corresponds to the solution commented in this issue?
> 
> @PabloRdrRbl IIRC the latest release is 0.3.0

@stuartarchibald, thanks for your answer. But I have tested 0.3.0 and I still have the same issues reported in this issue. I wonder if the pull request #54 is still to be released.

**Comment by esc** [comment]
> > > Hello, which is the version that corresponds to the solution commented in this issue?
> > 
> > 
> > @PabloRdrRbl IIRC the latest release is 0.3.0
> 
> @stuartarchibald, thanks for your answer. But I have tested 0.3.0 and I still have the same issues reported in this issue. I wonder if the pull request #54 is still to be released.

@PabloRdrRbl thank you for looking into this. I just downloaded the latest numba-scipy 0.3.0 from PyPi:

https://pypi.org/project/numba-scipy/#files

Unpacking and looking at the files, `signature.py` is indeed in the version created by #54 :

```
 💣 zsh» tar xvzf numba-scipy-0.3.0.tar.gz
x numba-scipy-0.3.0/
x numba-scipy-0.3.0/LICENSE
x numba-scipy-0.3.0/MANIFEST.in
x numba-scipy-0.3.0/PKG-INFO
x numba-scipy-0.3.0/README.rst
x numba-scipy-0.3.0/numba_scipy/
x numba-scipy-0.3.0/numba_scipy/__init__.py
x numba-scipy-0.3.0/numba_scipy/_version.py
x numba-scipy-0.3.0/numba_scipy/special/
x numba-scipy-0.3.0/numba_scipy/special/__init__.py
x numba-scipy-0.3.0/numba_scipy/special/overloads.py
x numba-scipy-0.3.0/numba_scipy/special/signatures.py
x numba-scipy-0.3.0/numba_scipy/tests/
x numba-scipy-0.3.0/numba_scipy/tests/__init__.py
x numba-scipy-0.3.0/numba_scipy/tests/test_special.py
x numba-scipy-0.3.0/numba_scipy.egg-info/
x numba-scipy-0.3.0/numba_scipy.egg-info/PKG-INFO
x numba-scipy-0.3.0/numba_scipy.egg-info/SOURCES.txt
x numba-scipy-0.3.0/numba_scipy.egg-info/dependency_links.txt
x numba-scipy-0.3.0/numba_scipy.egg-info/entry_points.txt
x numba-scipy-0.3.0/numba_scipy.egg-info/not-zip-safe
x numba-scipy-0.3.0/numba_scipy.egg-info/requires.txt
x numba-scipy-0.3.0/numba_scipy.egg-info/top_level.txt
x numba-scipy-0.3.0/setup.cfg
x numba-scipy-0.3.0/setup.py
x numba-scipy-0.3.0/versioneer.py
 💣 zsh» cd numba-scipy-0.3.0
 💣 zsh» ls
LICENSE  MANIFEST.in  PKG-INFO  README.rst  numba_scipy  numba_scipy.egg-info  setup.cfg  setup.py  versioneer.py
 💣 zsh» cat numba_scipy/special/signatures.py
import collections
import ctypes
import re

import numba
import scipy.special.cython_special as cysc
from numba.extending import get_cython_function_address

CYTHON_TO_NUMBA = {
    'double': numba.types.float64,
    'float': numba.types.float32,
    'long': numba.types.long_,
}

NUMBA_TO_CTYPES = {
    numba.types.float64: ctypes.c_double,
    numba.types.float32: ctypes.c_float,
    numba.types.long_: ctypes.c_long,
}


def parse_capsule_name(capsule):
    # There isn't a Python equivalent to `PyCapsule_GetName`, so
    # resort to a hacky method for finding the signature.
    match = re.match(
        '<capsule object "(?P<signature>.+)" at 0x[A-Fa-f0-9]+>',
        str(capsule),
    )
    if match is None:
        raise ValueError('Unexpected capsule name {}'.format(capsule))

    signature = match.group('signature')
    match = re.match('(?P<return_type>.+) \\((?P<arg_types>.+)\\)', signature)
    if match is None:
        raise ValueError('Unexpected signature {}'.format(signature))

    args = [
        arg_type for arg_type in match.group('arg_types').split(', ')
        if arg_type != 'int __pyx_skip_dispatch'
    ]
    return [match.group('return_type')] + args


def de_mangle_function_name(mangled_name):
    match = re.match('(__pyx_fuse(_[0-9])*)?(?P<name>.+)', mangled_name)
    if match is None:
        raise ValueError('Unexpected mangled name {}'.format(mangled_name))

    return match.group('name')


def get_signatures_from_pyx_capi():
    signature_to_pointer = {}

    for mangled_name, capsule in cysc.__pyx_capi__.items():
        numba_signature = [
            CYTHON_TO_NUMBA.get(t) for t in parse_capsule_name(capsule)
        ]
        if any(t is None for t in numba_signature):
            # We don't know how to handle this kernel yet.
            continue

        signature_to_pointer[(mangled_name, *numba_signature)] = capsule

    return signature_to_pointer


def generate_signatures_dicts(signature_to_pointer):
    name_to_numba_signatures = collections.defaultdict(list)
    name_and_types_to_pointer = {}
    for mangled_name, *signature in signature_to_pointer.keys():
        name = de_mangle_function_name(mangled_name)
        name_to_numba_signatures[name].append(
            tuple(signature[1:])
        )

        key = (name,) + tuple(signature[1:])

        address = (
            get_cython_function_address('scipy.special.cython_special', mangled_name)
        )
        ctypes_signature = [NUMBA_TO_CTYPES[t] for t in signature]
        ctypes_cast = (
            ctypes.CFUNCTYPE(*ctypes_signature)
        )
        name_and_types_to_pointer[key] = ctypes_cast(address)

    name_to_numba_signatures = {
        name: tuple(signatures)
        for name, signatures in name_to_numba_signatures.items()
    }
    return name_to_numba_signatures, name_and_types_to_pointer


signature_to_pointer = get_signatures_from_pyx_capi()
name_to_numba_signatures, name_and_types_to_pointer = generate_signatures_dicts(signature_to_pointer)
```

This means, you are probably having a different issue which may exhibit similar symptoms. My suggestion would be to open up a new issue stating:

* What you attempted?
* What you expected?
* What happened instead?

Thank would be most kind and I hope that this way we can help you to get numba-scipy working for you!

**Comment by PabloRdrRbl** [comment]
> 
> 
> > > > Hello, which is the version that corresponds to the solution commented in this issue?
> > > 
> > > 
> > > @PabloRdrRbl IIRC the latest release is 0.3.0
> > 
> > 
> > @stuartarchibald, thanks for your answer. But I have tested 0.3.0 and I still have the same issues reported in this issue. I wonder if the pull request #54 is still to be released.
> 
> @PabloRdrRbl thank you for looking into this. I just downloaded the latest numba-scipy 0.3.0 from PyPi:
> 
> https://pypi.org/project/numba-scipy/#files
> 
> Unpacking and looking at the files, `signature.py` is indeed in the version created by #54 :
> 
> ```
>  💣 zsh» tar xvzf numba-scipy-0.3.0.tar.gz
> x numba-scipy-0.3.0/
> x numba-scipy-0.3.0/LICENSE
> x numba-scipy-0.3.0/MANIFEST.in
> x numba-scipy-0.3.0/PKG-INFO
> x numba-scipy-0.3.0/README.rst
> x numba-scipy-0.3.0/numba_scipy/
> x numba-scipy-0.3.0/numba_scipy/__init__.py
> x numba-scipy-0.3.0/numba_scipy/_version.py
> x numba-scipy-0.3.0/numba_scipy/special/
> x numba-scipy-0.3.0/numba_scipy/special/__init__.py
> x numba-scipy-0.3.0/numba_scipy/special/overloads.py
> x numba-scipy-0.3.0/numba_scipy/special/signatures.py
> x numba-scipy-0.3.0/numba_scipy/tests/
> x numba-scipy-0.3.0/numba_scipy/tests/__init__.py
> x numba-scipy-0.3.0/numba_scipy/tests/test_special.py
> x numba-scipy-0.3.0/numba_scipy.egg-info/
> x numba-scipy-0.3.0/numba_scipy.egg-info/PKG-INFO
> x numba-scipy-0.3.0/numba_scipy.egg-info/SOURCES.txt
> x numba-scipy-0.3.0/numba_scipy.egg-info/dependency_links.txt
> x numba-scipy-0.3.0/numba_scipy.egg-info/entry_points.txt
> x numba-scipy-0.3.0/numba_scipy.egg-info/not-zip-safe
> x numba-scipy-0.3.0/numba_scipy.egg-info/requires.txt
> x numba-scipy-0.3.0/numba_scipy.egg-info/top_level.txt
> x numba-scipy-0.3.0/setup.cfg
> x numba-scipy-0.3.0/setup.py
> x numba-scipy-0.3.0/versioneer.py
>  💣 zsh» cd numba-scipy-0.3.0
>  💣 zsh» ls
> LICENSE  MANIFEST.in  PKG-INFO  README.rst  numba_scipy  numba_scipy.egg-info  setup.cfg  setup.py  versioneer.py
>  💣 zsh» cat numba_scipy/special/signatures.py
> import collections
> import ctypes
> import re
> 
> import numba
> import scipy.special.cython_special as cysc
> from numba.extending import get_cython_function_address
> 
> CYTHON_TO_NUMBA = {
>     'double': numba.types.float64,
>     'float': numba.types.float32,
>     'long': numba.types.long_,
> }
> 
> NUMBA_TO_CTYPES = {
>     numba.types.float64: ctypes.c_double,
>     numba.types.float32: ctypes.c_float,
>     numba.types.long_: ctypes.c_long,
> }
> 
> 
> def parse_capsule_name(capsule):
>     # There isn't a Python equivalent to `PyCapsule_GetName`, so
>     # resort to a hacky method for finding the signature.
>     match = re.match(
>         '<capsule object "(?P<signature>.+)" at 0x[A-Fa-f0-9]+>',
>         str(capsule),
>     )
>     if match is None:
>         raise ValueError('Unexpected capsule name {}'.format(capsule))
> 
>     signature = match.group('signature')
>     match = re.match('(?P<return_type>.+) \\((?P<arg_types>.+)\\)', signature)
>     if match is None:
>         raise ValueError('Unexpected signature {}'.format(signature))
> 
>     args = [
>         arg_type for arg_type in match.group('arg_types').split(', ')
>         if arg_type != 'int __pyx_skip_dispatch'
>     ]
>     return [match.group('return_type')] + args
> 
> 
> def de_mangle_function_name(mangled_name):
>     match = re.match('(__pyx_fuse(_[0-9])*)?(?P<name>.+)', mangled_name)
>     if match is None:
>         raise ValueError('Unexpected mangled name {}'.format(mangled_name))
> 
>     return match.group('name')
> 
> 
> def get_signatures_from_pyx_capi():
>     signature_to_pointer = {}
> 
>     for mangled_name, capsule in cysc.__pyx_capi__.items():
>         numba_signature = [
>             CYTHON_TO_NUMBA.get(t) for t in parse_capsule_name(capsule)
>         ]
>         if any(t is None for t in numba_signature):
>             # We don't know how to handle this kernel yet.
>             continue
> 
>         signature_to_pointer[(mangled_name, *numba_signature)] = capsule
> 
>     return signature_to_pointer
> 
> 
> def generate_signatures_dicts(signature_to_pointer):
>     name_to_numba_signatures = collections.defaultdict(list)
>     name_and_types_to_pointer = {}
>     for mangled_name, *signature in signature_to_pointer.keys():
>         name = de_mangle_function_name(mangled_name)
>         name_to_numba_signatures[name].append(
>             tuple(signature[1:])
>         )
> 
>         key = (name,) + tuple(signature[1:])
> 
>         address = (
>             get_cython_function_address('scipy.special.cython_special', mangled_name)
>         )
>         ctypes_signature = [NUMBA_TO_CTYPES[t] for t in signature]
>         ctypes_cast = (
>             ctypes.CFUNCTYPE(*ctypes_signature)
>         )
>         name_and_types_to_pointer[key] = ctypes_cast(address)
> 
>     name_to_numba_signatures = {
>         name: tuple(signatures)
>         for name, signatures in name_to_numba_signatures.items()
>     }
>     return name_to_numba_signatures, name_and_types_to_pointer
> 
> 
> signature_to_pointer = get_signatures_from_pyx_capi()
> name_to_numba_signatures, name_and_types_to_pointer = generate_signatures_dicts(signature_to_pointer)
> ```
> 
> This means, you are probably having a different issue which may exhibit similar symptoms. My suggestion would be to open up a new issue stating:
> 
>     * What you attempted?
> 
>     * What you expected?
> 
>     * What happened instead?
> 
> 
> Thank would be most kind and I hope that this way we can help you to get numba-scipy working for you!

Thanks @esc, I have open a new issue under #64.
