### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by esc** [numba/numba-scipy#80]
Probably some of the github actions logic will need to be adapted.

**Comment by esc** [comment]
#87 fixes CI config and docs, once merged, all that is needed is a rename in the GitHub `settings` tab for the repo.

**Comment by sklam** [comment]
merged #87. @esc, i'll let you do the changes in Github `settings` since you have experience doing it.

**Comment by esc** [comment]
<img width="1238" alt="Screen Shot 2022-08-05 at 08 05 09" src="https://user-images.githubusercontent.com/41563/183012229-a76bc7bd-c7a2-4f3f-99f5-0f0f661db78c.png">

it is done.

**Comment by esc** [comment]
GHA suceded fine for the `main` branch.
