### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by sklam** [numba/numba-scipy#83]
- [x] merge changelog for 0.3.1 https://github.com/numba/numba-scipy/pull/84
- [x] port to `release0.3` branch https://github.com/numba/numba-scipy/pull/85
- [x] create `0.3.1` tag on branch
  - https://github.com/numba/numba-scipy/releases/tag/0.3.1 
- [x] push branch and tag
- [x] Check that Github Actions created and uploaded PyPi release
  - https://pypi.org/project/numba-scipy/0.3.1/ 
- [x] Check that Github Actions create a conda package
- [x] Ensure conda package in correct channel (`numba/label/main`)
- [x] Create Discourse announcement (https://numba.discourse.group/t/numba-scipy-0-3-1/1425)
- [x] Create Twitter announcement (https://twitter.com/numba_jit/status/1542528762125975552)
- ~Tag next dev release on `master` and open changelog for 0.5.*~

**Comment by esc** [comment]
@sklam it's a wrap!
