### ISSUE TITLE
triangular solver

### ISSUE THREAD

**Issue by samotto1** [numba/numba-scipy#91]
## Feature request

Hi,

I would like to be able to solve symmetric positive-definite linear systems in Numba using Cholesky factorization. While the Cholesky factorization is implemented, there is no triangular solver! It would be wonderful if a triangular solver could be implemented so that I can take advantage of the Cholesky function. Thanks.

Sam

**Comment by stuartarchibald** [comment]
I transferred this in from `numba/numba` (was issue 6394) as it's a request for supporting a feature in `scipy`.

**Comment by agramfort** [comment]
@gmarkall @stuartarchibald any chance this can be looked into soon? thanks
