### ISSUE TITLE
Package new release to include latest patch change (version 0.3.2)

### ISSUE THREAD

**Issue by oliverfunk** [numba/numba-scipy#97]
#90 bumped the scipy version to <1.11.0 but these changes have yet to be packaged and published to Pypi.

Would it be possible to cut a release and publish it?

Many thanks!

**Comment by esc** [comment]
@je-cook soon, I hope. Unfortunately, it seems I don't know the release process for this tool anymore. I looked in the docs and couldn't find anything either. Is it just a matter of updating the release notes and then tagging? I see there is a GHA and I do have a token on PyPi to push to there.

**Comment by esc** [comment]
Folks, this is still on my list, but I am currently spending most of my time on Nmba itself. I hope to get to this eventually, probably in the Q1 2024 timeframe. If anyone wants to prep things here, it would be useful to work out how to release this. It maybe just a matter of creating some release notes and then making a git tag, but probably gathering some more evidence on what we did in the past would be a good idea.

**Comment by je-cook** [comment]
Thanks, @esc thats no problem, sorry for the slow reply on my part. It looks like the "deploy release" action has never been used (or at least there is no history in the actions list). Its 2 years old and doesnt ever look to have been updated. 

In the action at least it looks like as soon as a tag has been made it will be pushed to pypi. There will need to be a slight update as the conda env created for the wheel build still has a pinned scipy.

It looks like previous releases may have happened manually with an update to the [CHANGE_LOG](https://github.com/numba/numba-scipy/blob/main/CHANGE_LOG).  

Maybe this is a good opportunity to do #94 although I have no idea how much work that is past possibly some dependabot setup. I will try and find some time to look into that unless someone beats me to it (maybe @oliverfunk?) !

**Comment by esc** [comment]
@je-cook thank you for looking into this. I've managed to look at this again and yes, it just seems to be a matter of:

* create release notes in a PR
* merge that PR and tag

With any luck the GitHub action will run and push the build artifact to PyPi. I'm getting closer and closer to having some time for this but if anyone would like to initiate the process with a starter-patch, I'd be happy to review, merge and tag that! I think all recent merges on `main` should be included in the release notes along with a short blurb highlighting any noteworthy features or bug reports. Numba has a script here https://github.com/numba/numba/blob/main/maint/gitlog2changelog.py -- which will generate a list of merged PRs and their authors. It probably won't work out of the box for numba-scipy, but I can image it can be jerry-rigged with minimal effort to produce something suitable.

**Comment by esc** [comment]
Still a bit rough, with readthedocs being broken and 3.12 missing, but it's a start: https://numba.discourse.group/t/ann-numba-scipy-0-4-0/2504
